version: 2.1

orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.8.10
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "colearnapp/requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r colearnapp/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "colearnapp/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: lint
          command: |
            . venv/bin/activate
            pylint colearnapp/colearnapp/ colearnapp/users/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - sonarcloud/scan
      
  build-and-push:
    docker:
      - image: cimg/python:3.8.10
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t beawolf/colearnapp:$CIRCLE_BUILD_NUM -t beawolf/colearnapp:latest ./colearnapp
      - run: docker push --all-tags beawolf/colearnapp
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
          platform: managed
          region: europe-west1
          service-name: colearnapp
          unauthenticated: true

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
      - build-and-push:
          requires:
            - test-and-lint
