version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "colearnapp/requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r colearnapp/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "colearnapp/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: lint
          command: |
            . venv/bin/activate
            pylint colearnapp/colearnapp/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 colearnapp/manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
